/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_natve_main_Main */

#ifndef _Included_com_natve_main_Main
#define _Included_com_natve_main_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_natve_main_Main
 * Method:    helloC
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_natve_main_Main_helloC
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
